package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Nikro
	 */
	public class fadsa extends Sprite 
	{
		private static var ACE:String = 'ACE';
		private static var BROOCH:String = 'BROOCH';
		private static var PENDANT:String = 'PENDANT';
		private static var KING:String = 'KING';
		private static var RING:String = 'RING';
		private static var JACK:String = 'JACK';
		private static var SUN:String = 'SUN';
		private static var NINE:String = 'NINE';
		private static var QUEEN:String = 'QUEEN';
		private static var STATUE:String = 'STATUE';
		private static var PYRAMID:String = 'PYRAMID';
		private static var TEN:String = 'TEN';
		private static var MOON:String = 'MOON';

		
		public  const REEL_0_99:Array = new Array(ACE, BROOCH, TEN, KING, SUN, QUEEN, JACK, BROOCH, TEN, JACK, PENDANT, ACE, TEN, QUEEN, JACK, BROOCH, ACE, NINE, TEN, STATUE, ACE, QUEEN, KING, TEN, BROOCH, QUEEN, TEN, MOON, NINE, JACK, PENDANT, TEN, ACE, QUEEN, BROOCH, TEN, JACK, KING, QUEEN, ACE, BROOCH, NINE, JACK, RING, NINE, ACE, QUEEN, TEN, BROOCH, JACK, NINE, ACE, MOON, JACK, QUEEN, RING, TEN, QUEEN, JACK, BROOCH, TEN, ACE, QUEEN, TEN, JACK, BROOCH, ACE, JACK, SUN, QUEEN, JACK, BROOCH, TEN, JACK, PENDANT, QUEEN, TEN, NINE, JACK, BROOCH, ACE, NINE, TEN, STATUE, ACE, QUEEN, KING, JACK, BROOCH, QUEEN, TEN, MOON, NINE, JACK, PENDANT, TEN, ACE, QUEEN, BROOCH, TEN, JACK, BROOCH, QUEEN, ACE, BROOCH, NINE, JACK, RING, NINE, ACE, QUEEN, TEN, BROOCH, KING, JACK, ACE, MOON, NINE, QUEEN, RING, TEN);
        public  const REEL_1_99:Array = new Array(PENDANT, KING, ACE, RING, PYRAMID, ACE, TEN, QUEEN, BROOCH, KING, QUEEN, RING, KING, QUEEN, BROOCH, ACE, KING, PYRAMID, ACE, KING, STATUE, TEN, QUEEN, PYRAMID, ACE, BROOCH, KING, QUEEN, PENDANT, ACE, JACK, SUN, ACE, JACK, BROOCH, KING, PYRAMID, RING, QUEEN, KING, MOON, ACE, QUEEN, BROOCH, ACE, PYRAMID, JACK, NINE, RING, QUEEN, ACE, KING, STATUE, JACK, QUEEN, ACE, PYRAMID, JACK, KING, PENDANT, JACK, RING, ACE, PYRAMID, PENDANT, KING, ACE, BROOCH, QUEEN, PENDANT, TEN, QUEEN, BROOCH, KING, NINE, PYRAMID, KING, QUEEN, BROOCH, ACE, KING, SUN, QUEEN, KING, PYRAMID, TEN, QUEEN, JACK, ACE, BROOCH, NINE, QUEEN, PYRAMID, ACE, JACK, MOON, QUEEN, ACE, BROOCH, KING, NINE, RING, QUEEN, KING, PYRAMID, JACK, QUEEN, BROOCH, ACE, KING, STATUE, NINE, RING, QUEEN, PYRAMID, KING, STATUE, JACK, NINE, BROOCH, ACE);
       
        public  const REEL_2_99:Array = new Array(JACK, TEN, PENDANT, ACE, KING, TEN, RING, NINE, STATUE, KING, PENDANT, NINE, TEN, KING, RING, NINE, ACE, STATUE, TEN, NINE, PENDANT, KING, TEN, MOON, ACE, NINE, PENDANT, KING, JACK, STATUE, NINE, TEN, SUN, QUEEN, NINE, PENDANT, QUEEN, TEN, STATUE, QUEEN, NINE, RING, KING, TEN, PENDANT, ACE, TEN, MOON, NINE, KING, PENDANT, JACK, TEN, RING, ACE, NINE, PENDANT, KING, ACE, STATUE, KING, TEN, NINE, RING, JACK, TEN, PENDANT, JACK, STATUE, TEN, RING, NINE, JACK, KING, PENDANT, NINE, TEN, KING, RING, NINE, ACE, STATUE, TEN, JACK, PENDANT, KING, TEN, MOON, ACE, NINE, PENDANT, KING, JACK, BROOCH, NINE, TEN, SUN, QUEEN, NINE, PENDANT, QUEEN, TEN, BROOCH, QUEEN, NINE, RING, JACK, TEN, PENDANT, ACE, JACK, MOON, NINE, KING, PENDANT, JACK, TEN, RING, ACE, NINE, PENDANT);
        public  const REEL_3_99:Array = new Array(STATUE, NINE, SUN, JACK, BROOCH, QUEEN, MOON, TEN, PENDANT, NINE, STATUE, TEN, BROOCH, KING, RING, QUEEN, STATUE, TEN, PENDANT, KING, MOON, NINE, STATUE, TEN, RING, JACK, SUN, KING, BROOCH, TEN, STATUE, JACK, SUN, ACE, PENDANT, KING, MOON, TEN, PENDANT, JACK, RING, NINE, STATUE, TEN, SUN, QUEEN, PENDANT, TEN, MOON, JACK, STATUE, NINE, PENDANT, KING, MOON, JACK, STATUE, NINE, PENDANT, QUEEN, RING, TEN, MOON, JACK, STATUE, NINE, SUN, JACK, RING, KING, MOON, JACK, PENDANT, NINE, MOON, TEN, BROOCH, KING, RING, QUEEN, STATUE, KING, PENDANT, JACK, ACE, MOON, TEN, BROOCH, NINE, RING, QUEEN, KING, BROOCH, TEN, JACK, STATUE, NINE, ACE, PENDANT, KING, QUEEN, SUN, TEN, JACK, RING, NINE, ACE, STATUE, KING, QUEEN, PENDANT, TEN, RING, JACK, NINE, STATUE, KING, PENDANT, TEN, MOON, JACK);
        public  const REEL_4_99:Array = new Array(STATUE, NINE, SUN, JACK, BROOCH, QUEEN, RING, ACE, PENDANT, NINE, SUN, QUEEN, BROOCH, KING, RING, QUEEN, SUN, TEN, PENDANT, KING, MOON, NINE, STATUE, TEN, RING, ACE, SUN, QUEEN, BROOCH, TEN, RING, JACK, SUN, ACE, BROOCH, KING, MOON, ACE, PENDANT, QUEEN, SUN, NINE, RING, TEN, SUN, QUEEN, PENDANT, TEN, MOON, ACE, STATUE, NINE, PENDANT, KING, MOON, JACK, STATUE, NINE, MOON, QUEEN, RING, TEN, MOON, JACK, STATUE, NINE, SUN, JACK, RING, KING, MOON, JACK, PENDANT, NINE, MOON, TEN, BROOCH, KING, MOON, QUEEN, RING, KING, PENDANT, JACK, MOON, TEN, BROOCH, NINE, SUN, QUEEN, BROOCH, KING, MOON, ACE, STATUE, NINE, MOON, ACE, BROOCH, QUEEN, SUN, TEN, RING, JACK, SUN, ACE, STATUE, KING, MOON, ACE, RING, JACK, MOON, NINE, STATUE, KING, PENDANT, TEN, MOON, JACK, ACE);
		
		public function fadsa() 
		{
			for (var i:int = 0; i < 5; i++)
			{
				var a:Array = this['REEL_' + i + '_99'];
				
				trace(a.join('\n'));
				trace('\n\n');
			}
		}
		
	}

}